### ISSUE TITLE
Data visualization: grid lines

### ISSUE THREAD

**Issue by noahmclean** [CIRDLES/Tripoli#175]
In "OnPeak Intensities by Time" tab for Preview/Review, make data easier to read by:

Decreasing the number of horizontal grid lines roughly by a factor of two.  The horizontal gridlines for the window are used largely qualitatively, to guide the eye and give a quick eyeballed estimate of magnitude.  Extra grid lines clutter the plot.

<img width="932" alt="Screenshot 2023-10-26 at 9 30 35 AM" src="https://github.com/CIRDLES/Tripoli/assets/7665736/80770e28-8123-458d-8c26-4e949813c86f">

**Comment by bowring** [comment]
Marking this as a future user preference per plot type.  Consider starting a discussion on user preferences.
