### ISSUE TITLE
Data visualization: block view

### ISSUE THREAD

**Issue by noahmclean** [CIRDLES/Tripoli#177]
In "OnPeak Intensities by Time" tab for Preview/Review, make data faster to navigate by:

Use the double-click gesture on a block to "Sculpt this Block" -- i.e., zoom in to the block so that its x-axis limits match the plot box.  Currently, "Sculpt this block" is accessed with a right-click and then a choice from a pop-up menu, and a double-click seems to hide the top menu.  

I don't see much of a use-case for hiding the top menu -- it doesn't gain much extra screen space -- and the block view is likelier to be used more frequently.  A double-click gesture will make the block view easier to access and encourage users to zoom in on more complicated data.

**Comment by bowring** [comment]
see next version 0.3.6 soon
