### ISSUE TITLE
OnPeak Intensities - zoom box limit freeze

### ISSUE THREAD

**Issue by noahmclean** [CIRDLES/Tripoli#186]
In the OnPeak Intensities by Time tab of the Review/Preview And Sculpt Data windows, you can left-click and drag to create a zoom box window.  When that box is dragged over to the far right limit or far left limit of the plot window, releasing the left mouse button does not result in a zoom.  Instead, the blue zoom box remains superimposed on the plot and there is no zoom.  Left-clicking anywhere in the plot space clears the zoom box, so it's not a fatal error.

**Comment by bowring** [comment]
fixed in v0.3.8
