### ISSUE TITLE
Sculpt problems

### ISSUE THREAD

**Issue by ryanickert** [CIRDLES/Tripoli#247]
The attached file is a TIMSDP file but I renamed the file so it would upload.  When in tiled mode, the sculpt box will not follow the mouse and make it hard or impossible to sculpt Perc_BaPO4_on_202.

For Prec_Decrease I can only scuplt in one direction and only one cycle (of the low outliers) at one time.

Tripoli Version: 0.5.3
Java Version: 21.0.3
JavaFX Version: 21.0.3+1
[D218_Pb-6894.txt](https://github.com/CIRDLES/Tripoli/files/15378488/D218_Pb-6894.txt)

OS: Windows 10 10.0

Issue details:

**Comment by ryanickert** [comment]
Looked at this in a bit more detail - it looks like the lack of ability to fully drag might be some sort of lag issue?  If I do it more slowly the box will expand.  I still can't sculpt the low early cycle from block 3 or the late cycle in block 6 (from Perc_BaPO4_on_202) when in tiled mode.  It works fine in full screen mode, so it might be related to the box boundaries not being equivalent to the block boundaries on the plot?  I also can't sculpt at all on Ratio 206/207 but I can on other ratios.  I can build the box but it won't reject any cycles.  Doesn't work in tiled or full screen mode.

**Comment by noahmclean** [comment]
Thanks @ryanickert!  I've been able to reproduce your problem on my Mac running Tripoli 0.5.3.

**Comment by bowring** [comment]
this will be fixed when we get selections across block boundaries like OGTripoli
