### ISSUE TITLE
Replicate "ignore" functionality from OGTripoli

### ISSUE THREAD

**Issue by ryanickert** [CIRDLES/Tripoli#248]
Please replicate the "ignore" functionality from OG Tripoli.  Have a button that will instruct tripoli to automatically rescale the data and ignore data that has been sculpted out (rejected).  Please also allow a user to sync the "ignore" between multiple ratios.

**Comment by noahmclean** [comment]
I think this button will also help with some re-scaling issues, where it is difficult to zoom in on precise data after rejecting a very imprecise block (e.g., if then run goes for a couple blocks after the beam dies).

**Comment by bowring** [comment]
see v0.5.4
