### ISSUE TITLE
Unexpected boxes appear on plot window resize

### ISSUE THREAD

**Issue by noahmclean** [CIRDLES/Tripoli#251]
Tripoli Version: 0.5.3
Java Version: 17.0.8.1
JavaFX Version: 17.0.8+1+b01
OS: Mac OS X 14.5

Issue details: If I open a dataset, switch some plots to 'sculpt mode', use the left-click drag action to draw a box around data to reject them, then resize the 'Tripoli PREVIEW and Sculpt Data' window, I see red or blue boxes appear inside most of the plots that I sculpted.  The boxes appear to be in random positions.

<img width="768" alt="Screenshot 2024-05-22 at 8 44 06 AM" src="https://github.com/CIRDLES/Tripoli/assets/7665736/59521540-3dde-4c15-b567-fcc4fdc8a099">

**Comment by bowring** [comment]
fixed in v0.5.4
