### ISSUE TITLE
Small screen issue

### ISSUE THREAD

**Issue by YakovYermakov** [CIRDLES/Tripoli#264]
While working on the small screen (I have 13-inch laptop), you may see that one "inverted" button is not aligned properly.
https://github.com/CIRDLES/Tripoli/assets/130931450/3c9ead00-6226-4ed7-b1c0-563624f50121

**Comment by YakovYermakov** [comment]
Sorry, wrong media file

https://github.com/CIRDLES/Tripoli/assets/130931450/8e34bea5-6aeb-4974-a841-eed492108009

**Comment by bowring** [comment]
addressed in V0.5.6.  @YakovYermakov please make new issue if problem persists.  Cheers
