### ISSUE TITLE
Mean value not plotting

### ISSUE THREAD

**Issue by riouxm** [CIRDLES/Tripoli#272]
In version 0.5.6, when plotting in cycle mode, the mean value of the selected data is not plotting. It is possible to get it to plot by deselecting the last block of the dataset.

<img width="495" alt="PNG image" src="https://github.com/user-attachments/assets/8d3cf21f-87fd-4635-b710-c5db828fcca5">
<img width="497" alt="PNG image" src="https://github.com/user-attachments/assets/0c776587-3651-4349-a16d-00227279a420">

**Comment by bowring** [comment]
fixed v0.5.7
