### ISSUE TITLE
Incorrect n

### ISSUE THREAD

**Issue by riouxm** [CIRDLES/Tripoli#282]
Tripoli currently reports an incorrect n for the data. As an example, the attached data file contains 225 cycles. When I plot the data, it indicates that n = 225/240, even though there are only 225 cycles and no data have been deselected.

[891_F19_735B_1271m iz18 Pb-8932.xls](https://github.com/user-attachments/files/17652802/891_F19_735B_1271m.iz18.Pb-8932.xls)

**Comment by bowring** [comment]
Fixed in v0.5.8
